before_cache:
- rm -rf $HOME/.m2/repository/org/antlr
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then sed -i '' 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        else sed -i 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        fi
- f="./.travis/before-install-$TRAVIS_OS_NAME-$TARGET.sh"; ! [ -x "$f" ] || "$f"
before_script:
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then sed -i '' 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;        else sed -i 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;        fi
cache:
  directories:
  - $HOME/.m2
  - $HOME/Library/Caches/Antlr4
  - $HOME/Library/Caches/Homebrew
  timeout: 600
language: java
matrix:
  include:
  - addons:
      apt:
        packages:
        - g++-5
        - uuid-dev
        - clang-3.7
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
    compiler: clang
    env:
    - TARGET=cpp
    - CXX=g++-5
    - GROUP=LEXER
    jdk: openjdk7
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: main-test
  - addons:
      apt:
        packages:
        - g++-5
        - uuid-dev
        - clang-3.7
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
    compiler: clang
    env:
    - TARGET=cpp
    - CXX=g++-5
    - GROUP=PARSER
    jdk: openjdk7
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: main-test
  - addons:
      apt:
        packages:
        - g++-5
        - uuid-dev
        - clang-3.7
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
    compiler: clang
    env:
    - TARGET=cpp
    - CXX=g++-5
    - GROUP=RECURSION
    jdk: openjdk7
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: main-test
  - compiler: clang
    env:
    - TARGET=cpp
    - GROUP=LEXER
    os: osx
    osx_image: xcode9
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: extended-test
  - compiler: clang
    env:
    - TARGET=cpp
    - GROUP=PARSER
    os: osx
    osx_image: xcode9
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: extended-test
  - compiler: clang
    env:
    - TARGET=cpp
    - GROUP=RECURSION
    os: osx
    osx_image: xcode9
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: extended-test
  - compiler: clang
    env:
    - TARGET=swift
    - GROUP=LEXER
    os: osx
    osx_image: xcode9
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: main-test
  - compiler: clang
    env:
    - TARGET=swift
    - GROUP=PARSER
    os: osx
    osx_image: xcode9
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: main-test
  - compiler: clang
    env:
    - TARGET=swift
    - GROUP=RECURSION
    os: osx
    osx_image: xcode9
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: main-test
  - compiler: clang
    dist: trusty
    env:
    - TARGET=swift
    - GROUP=ALL
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: extended-test
  - env:
    - TARGET=dotnet
    - GROUP=LEXER
    os: osx
    osx_image: xcode9
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: extended-test
  - env:
    - TARGET=dotnet
    - GROUP=PARSER
    os: osx
    osx_image: xcode9
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: extended-test
  - env:
    - TARGET=dotnet
    - GROUP=RECURSION
    os: osx
    osx_image: xcode9
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: extended-test
  - env: TARGET=java
    jdk: openjdk7
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: extended-test
  - env: TARGET=java
    jdk: openjdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: extended-test
  - env: TARGET=java
    jdk: oraclejdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: smoke-test
  - env: TARGET=csharp
    jdk: openjdk7
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: extended-test
  - dist: trusty
    env:
    - TARGET=dotnet
    - GROUP=LEXER
    jdk: oraclejdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: main-test
  - dist: trusty
    env:
    - TARGET=dotnet
    - GROUP=PARSER
    jdk: openjdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: main-test
  - dist: trusty
    env:
    - TARGET=dotnet
    - GROUP=RECURSION
    jdk: oraclejdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: main-test
  - env: TARGET=python2
    jdk: openjdk7
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: extended-test
  - addons:
      apt:
        packages:
        - python3.5
        sources:
        - deadsnakes
    env: TARGET=python3
    jdk: openjdk7
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: main-test
  - dist: trusty
    env: TARGET=javascript
    jdk: openjdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: main-test
  - dist: trusty
    env: TARGET=go
    jdk: openjdk8
    os: linux
    script:
    - touch /tmp/NOW;echo SCRIPT_START $(date)
    - mvn test -B
    - echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
      -name TEST-*.xml -newer /tmp/NOW) | wc -l)
    stage: main-test
script:
- touch /tmp/NOW;echo SCRIPT_START $(date)
- cd runtime-testsuite; travis_wait 40 ../.travis/run-tests-$TARGET.sh
- echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
  -name TEST-*.xml -newer /tmp/NOW) | wc -l)
stages:
- smoke-test
- main-test
- extended-test
sudo: true
